# Generated by Django 4.2.27 on 2025-12-19 15:39

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostanadat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=20, verbose_name='نام سند')),
                ('file_document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'اسناد برای پرکردن دانش آموزان',
                'db_table': 'Mostanadat',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_photo', models.ImageField(upload_to=accounts.models.user_document_path, verbose_name='عکس پرسنلی دانش\u200cآموز / الصورة الشخصية للطالب')),
                ('id_card_front', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='تصویر روی مدرک هویتی / صورة الوجه الأمامي للهوية')),
                ('id_card_back', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='تصویر پشت مدرک هویتی / صورة الوجه الخلفي للهوية')),
                ('last_education_certificate', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='آخرین مدرک تحصیلی / آخر شهادة دراسية')),
                ('school_permission_certificate', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='مجوز معتبر مدرسه / تصريح المدرسة المعتمد')),
                ('document_request_register', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='درخواست ثبت\u200cنام / طلب التسجيل')),
                ('document_contract_finance', models.FileField(upload_to=accounts.models.user_document_path, verbose_name='قرارداد مالی / العقد المالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری / وقت الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی / آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر / المستخدم')),
            ],
            options={
                'verbose_name': 'مدارک کاربر',
                'verbose_name_plural': 'مدارک کاربران',
                'db_table': 'user_documents',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی / الرقم الوطني')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر / اسم الأب')),
                ('father_national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی پدر / الرقم الوطني للأب')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر محل سکونت / المدينة')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس دقیق / العنوان التفصيلي')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پاسپورت / رقم جواز السفر')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلگرام / رقم تيليجرام')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره واتساپ / رقم واتساب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر / المستخدم')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'db_table': 'profiles',
            },
        ),
    ]
