# Generated by Django 4.2.27 on 2025-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس دقیق / العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر محل سکونت / المدينة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر / اسم الأب'),
        ),
    ]
