# Generated by Django 4.2.27 on 2025-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostanadat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=20, verbose_name='نام سند')),
                ('file_document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'اسناد برای پرکردن دانش آموزان',
                'db_table': 'Mostanadat',
            },
        ),
    ]
